# Generated by Django 3.2.5 on 2021-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='a',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='b',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='c',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='d',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
